### ISSUE TITLE
Multiple errors on mv create world

### ISSUE THREAD

**Issue by SlimeDog** [echurchill/CityWorld#33]
CentOS Linux up-to-date

Spigot 1.13.2 latest
WorldEdit 7.0.0-SNAPSHOT;3997-ba8bde0
Multiverse-Core 2.6.0-b738
CityWorld 4.000

Initial software load did not create _plugins/CityWorld/_ directory. Thinking it might be created along with the first world, I attempted:
> mv create world_city normal -s 2000 -g CityWorld

The results:
- _plugins/CityWorld_ was created
- _plugins/CityWorld/config.yml_ was populated
- No schematics were created in _plugins/CityWorld_
- _UNIVERSE/world_city/_ was created with the following content (note: no _level.dat*_ files)
```
UNIVERSE/world_city/:
data  DIM1  DIM-1  playerdata  region  session.lock  uid.dat

UNIVERSE/world_city/data/: empty
UNIVERSE/world_city/DIM1/data/: empty
UNIVERSE/world_city/DIM-1/data/: empty
UNIVERSE/world_city/playerdata: empty
UNIVERSE/world_city/region/r.-1.0.mca
UNIVERSE/world_city/region/r.-1.-1.mca
```
- multiple log errors, starting with
```
[17:19:51] [Server thread/INFO]: CityWorld creating world test
[17:19:51] [Server thread/INFO]: [CityWorld] Found Minecraft v1.130, CityWorld is compatible - WOOT!
[17:19:51] [Server thread/INFO]: [CityWorld][Generator] Unknown world style , switching to NORMAL
[17:19:51] [Server thread/INFO]: CONSOLE: Starting creation of world 'world_city'...
[17:19:51] [Server thread/INFO]: CityWorld creating world world_city
[17:19:51] [Server thread/INFO]: [CityWorld] Found Minecraft v1.130, CityWorld is compatible - WOOT!
[17:19:51] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'world_city' - Env: NORMAL - Type: NORMAL & seed: 2000 & generator: CityWorld
[17:19:51] [Server thread/INFO]: -------- World Settings For [world_city] --------
[17:19:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[17:19:51] [Server thread/INFO]: Max TNT Explosions: 100
[17:19:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:19:51] [Server thread/INFO]: Entity Activation Range: An 48 / Mo 48 / Mi 32 / Tiv true
[17:19:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:19:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:19:51] [Server thread/INFO]: Random Lighting Updates: true
[17:19:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:19:51] [Server thread/INFO]: Mob Spawn Range: 6
[17:19:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Carrot Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Potato Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:19:51] [Server thread/INFO]: Item Despawn Rate: 6000
[17:19:51] [Server thread/INFO]: Item Merge Radius: 2.5
[17:19:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:19:51] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:19:51] [Server thread/INFO]: View Distance: 10
[17:19:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:19:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:19:52] [Server thread/INFO]: [CityWorld] ShapeProvider.populateLots FAILED
[17:19:52] [Server thread/INFO]:  \__Exception: null
[17:19:52] [Server thread/WARN]: java.lang.NullPointerException
[17:19:52] [Server thread/WARN]: 	at me.daddychurchill.CityWorld.Context.DataContext.getSchematics(DataContext.java:118)
[17:19:52] [Server thread/WARN]: 	at me.daddychurchill.CityWorld.Context.UrbanContext.populateMap(UrbanContext.java:33)
[17:19:52] [Server thread/WARN]: 	at me.daddychurchill.CityWorld.Plugins.ShapeProvider.populateLots(ShapeProvider.java:87)
[17:19:52] [Server thread/WARN]: 	at me.daddychurchill.CityWorld.Support.PlatMap.<init>(PlatMap.java:43)
[17:19:52] [Server thread/WARN]: 	at me.daddychurchill.CityWorld.CityWorldGenerator.getPlatMap(CityWorldGenerator.java:385)
[17:19:52] [Server thread/WARN]: 	at me.daddychurchill.CityWorld.CityWorldGenerator.generateChunkData(CityWorldGenerator.java:313)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.generator.CustomChunkGenerator.createChunk(CustomChunkGenerator.java:61)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTaskBase.a(SourceFile:13)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:75)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[17:19:52] [Server thread/WARN]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:677)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:2104)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[17:19:52] [Server thread/WARN]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
[17:19:52] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:109)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:268)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:210)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldProviderNormal.a(SourceFile:187)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:803)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:713)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:956)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:458)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[17:19:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[17:19:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[17:19:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[17:19:52] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[17:19:52] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[17:19:52] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[17:19:52] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[17:19:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:19:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by SlimeDog** [comment]
Same issues with CityWorld 4.01 and 4.02.

**Comment by echurchill** [comment]
First, that "not creating the plugin config" problem seems to keep popping up on Linux boxes. Very strange.

Do you have WorldEdit installed in your plugin folder? If so what version is it? 

Could you send the complete log to me at eddie at virtualchurchill dot com.

I will dig into this tomorrow morning

Thanks for the report, it helps a bunch.

**Comment by echurchill** [comment]
I think I figured out why the configs are being generated. Unlike most plugins I only create configs when world loads are triggered, not when it is enabled. I will likely change that because it causes nothing but confusion. 

Still looking at the schematic error

**Comment by SlimeDog** [comment]
> ... Unlike most plugins I only create configs when world loads are triggered, not when it is enabled. I will likely change that because it causes nothing but confusion...

For my money, most of the content of the current configuration is more data than configuration. Perhaps splitting out the default configuration in _config.yml_, then making a new (say) _worlds.yml_, with the world-specific data that is different from the defaults.

**Comment by SlimeDog** [comment]
Maybe has been isolated to non-standard location of worlds directory on start-up:
> spigot ... --universe OTHER_DIRECTORY ...

**Comment by SlimeDog** [comment]
Culprit was PhatLoots. I was using the updated-for-1.13 version @ [https://ci.articdive.de/job/PhatLoots/](https://ci.articdive.de/job/PhatLoots/) since Codimus hasn't updated the Spigot-tethered version.

Is PhatLoots still required to generated chest loot?

**Comment by echurchill** [comment]
I think this is fixed
