### ISSUE TITLE
ChunkPopulator fails with Spigot build 2568

### ISSUE THREAD

**Issue by SlimeDog** [echurchill/CityWorld#44]
Spigot 1.15.1 (Jenkins 2568)
CityWorld 4.100

This was not an issue with previous spigot build 1.15.1 (Jenkins 2564)

It may be related to [https://hub.spigotmc.org/jira/browse/SPIGOT-5515](https://hub.spigotmc.org/jira/browse/SPIGOT-5515)

Many errors like this (which are listed as WARN):
```
[22:04:13] [Server-Worker-4/INFO]: [CityWorld] ChunkPopulator FAILED
[22:04:13] [Server-Worker-4/INFO]:  \__Exception: null
[22:04:13] [Server-Worker-4/WARN]: java.lang.NullPointerException
[22:04:13] [Server-Worker-4/WARN]:      at me.daddychurchill.CityWorld.Support.PlatMap.<init>(PlatMap.java:43)
[22:04:13] [Server-Worker-4/WARN]:      at me.daddychurchill.CityWorld.CityWorldGenerator.getPlatMap(CityWorldGenerator.java:378)
[22:04:13] [Server-Worker-4/WARN]:      at me.daddychurchill.CityWorld.CityWorldGenerator.generateChunkData(CityWorldGenerator.java:306)
[22:04:13] [Server-Worker-4/WARN]:      at org.bukkit.craftbukkit.v1_15_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:102)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ChunkStatus.e(SourceFile:71)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ChunkStatus$d.doWork(SourceFile:258)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ChunkStatus.a(SourceFile:214)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$25(PlayerChunkMap.java:520)
[22:04:13] [Server-Worker-4/WARN]:      at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$23(PlayerChunkMap.java:518)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(SourceFile:83)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(SourceFile:123)
[22:04:13] [Server-Worker-4/WARN]:      at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(SourceFile:91)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[22:04:13] [Server-Worker-4/WARN]:      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by SlimeDog** [comment]
Note that the change was reverted in Spigot build 2569. All is well, until the change is reintroduced (at some point).

**Comment by echurchill** [comment]
I wonder why they want to make that change. You can have stacks of non-items in your inventory (blocks of ores for example). Oh well, thanks for the heads up. I will keep an eye out for the potential future change
