### ISSUE TITLE
Fatal error updating world to Spigot 1.16.1

### ISSUE THREAD

**Issue by SlimeDog** [echurchill/CityWorld#47]
Spigot 1.16.1
CityWorld

start with --force-upgrade produces lots of these:
```
[18:33:04] [Worker-Main-33/FATAL]: Failed to schedule load callback for chunk [-2, 16]
java.util.concurrent.CompletionException: java.lang.NoSuchFieldError: PIG_ZOMBIE
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ThreadedMailbox.e(SourceFile:94) [spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ThreadedMailbox.a(SourceFile:137) [spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ThreadedMailbox.run(SourceFile:105) [spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: java.lang.NoSuchFieldError: PIG_ZOMBIE
        at me.daddychurchill.CityWorld.Plugins.SpawnProvider.<init>(SpawnProvider.java:34) ~[?:?]
        at me.daddychurchill.CityWorld.CityWorldGenerator.initializeWorldInfo(CityWorldGenerator.java:231) ~[?:?]
        at me.daddychurchill.CityWorld.CityWorldGenerator.generateChunkData(CityWorldGenerator.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:118) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ChunkStatus.e(SourceFile:75) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ChunkStatus$d.doWork(SourceFile:263) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ChunkStatus.a(SourceFile:219) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$26(PlayerChunkMap.java:538) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$24(PlayerChunkMap.java:536) ~[spigot-1.16.1.jar-2020-06-24-1810:git-Spigot-758abbe-2b00831]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
        ... 11 more
```
Changing **PIG_ZOMBIE** to **ZOMBIFIED_PIGLIN** in plugins/CityWorld/{world}.yml resolved that issue. But then a lot of these:
```
[22:45:28] [Worker-Main-33/FATAL]: Failed to schedule load callback for chunk [-2, 15]
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R1.ReportedException: Exception generating new chunk
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_16_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.ThreadedMailbox.e(SourceFile:94) [spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.ThreadedMailbox.a(SourceFile:137) [spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.ThreadedMailbox.run(SourceFile:105) [spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: net.minecraft.server.v1_16_R1.ReportedException: Exception generating new chunk
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$26(PlayerChunkMap.java:551) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$24(PlayerChunkMap.java:536) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: Plugins must use createChunkData(World) rather than implementing ChunkData: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at org.bukkit.craftbukkit.v1_16_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:122) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.ChunkStatus.e(SourceFile:75) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.ChunkStatus$d.doWork(SourceFile:263) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.ChunkStatus.a(SourceFile:219) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$26(PlayerChunkMap.java:538) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.lambda$24(PlayerChunkMap.java:536) ~[spigot-1.16.1.jar-2020-06-24-2125:git-Spigot-758abbe-38de0b8]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
        ... 11 more
```

**Comment by Black-Hole** [comment]
This is fixed in newer builds of Spigot:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/68b98b3d24506a5c564973fea16d5a39ebf66d4e

**Comment by SlimeDog** [comment]
Indeed. Thank you.
